/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-08 15:29:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class boardView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	// 사용할 객체 초기화
	Connection conn = null;
	PreparedStatement pstmt = null;
	ResultSet rs = null;
	// 파라미터
	String num = request.getParameter("num");
	String pageNum = request.getParameter("pageNum");
	String searchType = request.getParameter("searchType");
	String searchText = request.getParameter("searchText");
	try {
		// 데이터베이스 객체 생성
		Class.forName("com.mysql.jdbc.Driver");
		conn = DriverManager.getConnection(
				//"jdbc:mysql://127.0.0.1:3306/blindhelperdb", "root", "1234");
				"jdbc:mysql://dxline1.cmlwnkhzvew3.us-west-2.rds.amazonaws.com:3306/dxlinedb", "lyu", "dladusdnr");
		// 조회수 증가 쿼리 실행
		pstmt = conn.prepareStatement("UPDATE BOARD SET HIT = HIT + 1 WHERE NUM = ?");
		pstmt.setString(1, num);
		pstmt.executeUpdate();
		// 게시물 상세 조회 쿼리 실행 
		pstmt = conn.prepareStatement(
			"SELECT NUM, SUBJECT, CONTENTS, WRITER, HIT, REG_DATE FROM BOARD "+ 
			"WHERE NUM = ?");
		pstmt.setString(1, num);
		rs = pstmt.executeQuery();
		rs.next();

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"></meta>\r\n");
      out.write("<title>게시판 상세보기</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t* {font-size: 9pt;}\r\n");
      out.write("\t.btn_align {width: 600px; text-align: right;}\r\n");
      out.write("\ttable tbody tr th {background-color: gray;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction goUrl(url) {\r\n");
      out.write("\t\tlocation.href=url;\r\n");
      out.write("\t}\r\n");
      out.write("\t// 삭제 체크\r\n");
      out.write("\tfunction deleteCheck(url) {\r\n");
      out.write("\t\tif (confirm('정말 삭제하시겠어요?')) {\r\n");
      out.write("\t\t\tlocation.href=url;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>");
      out.print(searchText);
      out.write("\r\n");
      out.write("\t<table border=\"1\" summary=\"게시판 상세조회\">\r\n");
      out.write("\t\t<caption>게시판 상세조회</caption>\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col width=\"100\" />\r\n");
      out.write("\t\t\t<col width=\"500\" />\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th align=\"center\">제목</th>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(rs.getString("SUBJECT") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th align=\"center\">작성자/조회수</th>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(rs.getString("WRITER") );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(rs.getInt("HIT") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th align=\"center\">등록 일시</th>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(rs.getString("REG_DATE") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">");
      out.print(rs.getString("CONTENTS") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<p class=\"btn_align\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"목록\" onclick=\"goUrl('boardList.jsp?pageNum=");
      out.print(pageNum);
      out.write("&amp;searchType=");
      out.print(searchType);
      out.write("&amp;searchText=");
      out.print(searchText);
      out.write("');\" />\r\n");
      out.write("\t\t<input type=\"button\" value=\"수정\" onclick=\"goUrl('boardModifyForm.jsp?num=");
      out.print(num);
      out.write("&amp;pageNum=");
      out.print(pageNum);
      out.write("&amp;searchType=");
      out.print(searchType);
      out.write("&amp;searchText=");
      out.print(searchText);
      out.write("');\" />\r\n");
      out.write("\t\t<input type=\"button\" value=\"삭제\" onclick=\"deleteCheck('boardProcess.jsp?mode=D&amp;num=");
      out.print(num);
      out.write("&amp;pageNum=");
      out.print(pageNum);
      out.write("&amp;searchType=");
      out.print(searchType);
      out.write("&amp;searchText=");
      out.print(searchText);
      out.write("');\" />\r\n");
      out.write("\t</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");

	} catch (Exception e) {
		e.printStackTrace();
	} finally {
		if (rs != null) rs.close();
		if (pstmt != null) pstmt.close();
		if (conn != null) conn.close();
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
