/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-11-21 05:48:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regFormImpl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01\r\n");
      out.write(" Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction chk() {\r\n");
      out.write("\t\tvar req = document.form.req.checked;\r\n");
      out.write("\t\tvar num = 0;\r\n");
      out.write("\t\tif (req == true) {\r\n");
      out.write("\t\t\tnum = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (num == 1) {\r\n");
      out.write("\t\t\tdocument.form.submit();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"개인정보 약관에 동의하셔야 합니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction nochk() {\r\n");
      out.write("\t\talert(\"동의하지 않으면 가입하실 수 없습니다\");\r\n");
      out.write("\t\tlocation.href = \"../log/index.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"style/memberStyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>회원가입 창</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"regFormImpl2.jsp\" name=\"form\" method=\"post\">\r\n");
      out.write("\t\t<table width=\"1400\" height=\"650\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"100%\" height=\"10%\">&nbsp; <b>회원가입</b> <br>\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"100%\" height=\"50%\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<p align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<span style=\"padding-left: 160px\"> 약관동의</span>\r\n");
      out.write("\t\t\t\t\t</p> <br> <textarea rows=\"20\" cols=\"150\">\r\n");
      out.write("가. 수집하는 개인정보의 항목첫째, 회사는 회원가 입, 원활한 고객상담, 각종 서비스의 제공을 위해 최초 회원가입 당시 아래와 같은 최소한의 개인정보를 필수항목으로 수집하고 있습니다.\r\n");
      out.write("회원가입\r\n");
      out.write("- 이름, 생년월일, 성별, 아이디, 비밀번호, 별명, 연락처(메일주소, 휴대폰 번호 중 선택), 가입인증정보\r\n");
      out.write("만14세 미만 아동 회원가입 \r\n");
      out.write("- 이름, 생년월일, 성별, 법정대리인 정보, 아이디, 비밀번호, 연락처 (메일주소, 휴대폰 번호 중 선택), 가입인증정보\r\n");
      out.write("단체아이디 회원가입 \r\n");
      out.write("- 단체아이디, 회사명, 대표자명, 대표 전화번호, 대표 이메일 주소, 단체주소, 관리자 아이디, 관리자 연락처, 관리자 부서/직위\r\n");
      out.write("- 선택항목 : 대표 홈페이지, 대표 팩스번호\r\n");
      out.write("둘째, 서비스 이용과정이나 사업처리 과정에서 아래와 같은 정보들이 자동으로 생성되어 수집될 수 있습니다.\r\n");
      out.write("- IP Address, 쿠키, 방문 일시, 서비스 이용 기록, 불량 이용 기록\r\n");
      out.write("셋째, 네이버 아이디를 이용한 부가 서비스 및 맞춤식 서비스 이용 또는 이벤트 응모 과정에서 해당 서비스의 이용자에 한해서만 개인정보 추가 수집이 발생할 수 있으며, 이러한 경우 별도의 동의를 받습니다. \r\n");
      out.write("넷째, 성인컨텐츠, 유료/게임 등 일부 서비스 이용시 관련 법률 준수를 위해 본인인증이 필요한 경우, 아래와 같은 정보들이 수집될 수 있습니다. \r\n");
      out.write("- 이름, 생년월일, 성별, 중복가입확인정보(DI), 암호화된 동일인 식별정보(CI), 휴대폰 번호(선택), 아이핀 번호(아이핀 이용시), 내/외국인 정보\r\n");
      out.write("다섯째, 유료 서비스 이용 과정에서 아래와 같은 결제 정보들이 수집될 수 있습니다. \r\n");
      out.write("- 신용카드 결제시 : 카드사명, 카드번호 등\r\n");
      out.write("- 휴대전화 결제시 : 이동전화번호, 통신사, 결제승인번호 등\r\n");
      out.write("- 계좌이체시 : 은행명, 계좌번호 등\r\n");
      out.write("- 상품권 이용시 : 상품권 번호\r\n");
      out.write("나. 개인정보 수집방법회사는 다음과 같은 방법으로 개인정보를 수집합니다. \r\n");
      out.write("- 홈페이지, 서면양식, 팩스, 전화, 상담 게시판, 이메일, 이벤트 응모, 배송요청\r\n");
      out.write("- 협력회사로부터의 제공 \r\n");
      out.write("- 생성정보 수집 툴을 통한 수집\r\n");
      out.write("   </textarea> <br> <input type=\"checkbox\" name=\"req\"> 개인정보 수집 및 이용에\r\n");
      out.write("\t\t\t\t\t동의합니다.\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\" valign=\"top\"><input type=\"button\" value=\"동의\"\r\n");
      out.write("\t\t\t\t\tonclick=\"chk()\" />&nbsp;&nbsp;&nbsp; <input type=\"button\"\r\n");
      out.write("\t\t\t\t\tvalue=\"동의하지 않습니다\" onclick=\"nochk()\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
