/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-11-21 07:08:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regFormImpl2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar right = 0;\r\n");
      out.write("\tfunction regChk() {\r\n");
      out.write("\t\tvar id = document.form.id.value;\r\n");
      out.write("\t\tvar regx = /^[a-zA-Z0-9]*$/;\r\n");
      out.write("\t\tvar chk1 = /\\d/;\r\n");
      out.write("\t\tvar chk2 = /[a-z]/i;\r\n");
      out.write("\t\tif (id.length == 0 || id == null) {\r\n");
      out.write("\t\t\talert(\"아이디를 입력하십시오\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!regx.test(id)) {\r\n");
      out.write("\t\t\talert(\"아이디는 영어, 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t\tdocument.form.id.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar pass = document.form.pass.value;\r\n");
      out.write("\t\tif (pass.length < 6 || pass == null) {\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력하십시오(6글자이상)\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (chk1.test(pass) && chk2.test(pass)) {\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"비밀번호는 영어, 숫자 조합입니다.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (right == 0) {\r\n");
      out.write("\t\t\talert(\"비밀번호가 동일한지 확인하시오\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar name = document.form.name.value;\r\n");
      out.write("\t\tif (name.length == 0 || name == null) {\r\n");
      out.write("\t\t\talert(\"이름을 입력하십시오\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar email1 = document.form.email1.value;\r\n");
      out.write("\t\tvar email2 = document.form.email1.value;\r\n");
      out.write("\t\tif (email1.length == 0 || email1 == null) {\r\n");
      out.write("\t\t\talert(\"이메일을 입력하십시오\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!regx.test(email1)) {\r\n");
      out.write("\t\t\talert(\"이메일은 영어, 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t\tdocument.form.email1.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (email2.length == 0 || email2 == null) {\r\n");
      out.write("\t\t\talert(\"이메일을 입력하십시오\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!regx.test(email2)) {\r\n");
      out.write("\t\t\talert(\"이메일은 영어, 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t\tdocument.form.email2.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar num_regx = /^[0-9]*$/;\r\n");
      out.write("\t\tvar ph2 = document.form.ph2.value;\r\n");
      out.write("\t\tif (ph2.length == 0 || ph2 == null) {\r\n");
      out.write("\t\t\talert(\"핸드폰번호를 입력하십시오\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar ph3 = document.form.ph3.value;\r\n");
      out.write("\t\tif (ph3.length == 0 || ph3 == null) {\r\n");
      out.write("\t\t\talert(\"핸드폰번호를 입력하십시오\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!num_regx.test(ph2) || !num_regx.test(ph3)) {\r\n");
      out.write("\t\t\talert(\"핸드폰번호는 숫자만 입력가능합니다\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar address = document.form.address.value;\r\n");
      out.write("\t\tif (address.length == 0 || address == null) {\r\n");
      out.write("\t\t\talert(\"주소를 입력하십시오\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.form.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction regCancel() {\r\n");
      out.write("\t\tlocation.href = \"../log/index.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction passchk() {\r\n");
      out.write("\t\tvar pass = document.form.pass.value;\r\n");
      out.write("\t\tvar pass2 = document.form.pass2.value;\r\n");
      out.write("\t\tif (pass2.length == 0 || pass2 == null) {\r\n");
      out.write("\t\t\tdocument.form.chk.value = \"비밀번호를 입력하세요\";\r\n");
      out.write("\t\t\tright = 0;\r\n");
      out.write("\t\t} else if (pass != pass2) {\r\n");
      out.write("\t\t\tdocument.form.chk.value = \"비밀번호가 다릅니다.\";\r\n");
      out.write("\t\t\tright = 0;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.form.chk.value = \"비밀번호가 동일합니다.\";\r\n");
      out.write("\t\t\tright = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction idcheck(){\r\n");
      out.write("\t\t var id = document.form.id.value;\r\n");
      out.write("\t\t if(id.length<1 || id==null){\r\n");
      out.write("\t\t  alert(\"중복체크할 아이디를 입력하십시오\");\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t var url = \"idCheck.jsp?id=\" + id;\r\n");
      out.write("\t\t window.open(url, \"get\", \"height = 180, width = 300\");\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"style/memberStyle.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>회원가입 창</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"regFormProc.jsp\" name=\"form\" method=\"post\">\r\n");
      out.write("\t\t<table width=\"900\" height=\"650\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"100%\" height=\"10%\">&nbsp;회원가입</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td height=\"60%\" align=\"center\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t<hr> <br>\r\n");
      out.write("\t\t\t\t\t<p align=\"left\" style=\"padding-left: 160px\">\r\n");
      out.write("\t\t\t\t\t\t<b>개인정보입력</b> <br> <br> ID : <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tsize=\"10\" maxlength=\"15\" name=\"id\">&nbsp;<input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"button\" value=\"중복 체크\" onclick=\"idcheck()\" /><br>\r\n");
      out.write("\t\t\t\t\t\t&nbsp; <br> 비밀번호 : <input type=\"password\" size=\"15\"\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength=\"20\" name=\"pass\"><br> <br> 비밀번호 확인 :\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" size=\"15\" maxlength=\"20\" name=\"pass2\"\r\n");
      out.write("\t\t\t\t\t\t\tonblur=\"passchk()\">&nbsp; <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border-width: 0px\" size=\"20\" name=\"chk\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"비밀번호를 입력하세요\" readonly=\"readonly\" class=\"danger1\">\r\n");
      out.write("\t\t\t\t\t\t<br> <br> 이름 : <input type=\"text\" size=\"13\"\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength=\"12\" name=\"name\"><br> <br> 이메일 : <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" size=\"15\" name=\"email1\">@<input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tsize=\"15\" name=\"email2\"><br> <br> 이메일 수신여부 : <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"radio\" name=\"sent\" value=\"ok\" checked=\"checked\">\r\n");
      out.write("\t\t\t\t\t\t수신함&nbsp;&nbsp; <input type=\"radio\" name=\"sent\" value=\"no\">\r\n");
      out.write("\t\t\t\t\t\t수신거절<br> <br> 휴대폰 : <span class=\"selectph1\"><select\r\n");
      out.write("\t\t\t\t\t\t\tname=\"ph1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t\t\t\t\t</select></span> - <input type=\"text\" name=\"ph2\" size=\"5\" maxlength=\"4\"> -\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"ph3\" size=\"5\" maxlength=\"4\"><br>\r\n");
      out.write("\t\t\t\t\t\t<br> 성별 : <input type=\"radio\" name=\"gender\" value=\"남자\"\r\n");
      out.write("\t\t\t\t\t\t\tchecked=\"checked\"> 남자&nbsp;&nbsp; <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"gender\" value=\"여자\"> 여자<br> <br> 생년월일 : <select\r\n");
      out.write("\t\t\t\t\t\t\tname=\"birth1\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 2013; i >= 1900; i--) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>년&nbsp; <select name=\"birth2\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 1; i <= 12; i++) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select> <select name=\"birth3\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 1; i <= 31; i++) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>일<br> <br> 주소 : <input type=\"text\" name=\"address\"\r\n");
      out.write("\t\t\t\t\t\t\tsize=\"15\" maxlength=\"15\">\r\n");
      out.write("\t\t\t\t\t<p align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"danger2\"> *주소는 (시/도)만 입력해주세요 (예: 경기도, 서울특별시,\r\n");
      out.write("\t\t\t\t\t\t\t경상남도 등) </span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t<hr> <br> <input type=\"button\" value=\"가입신청\"\r\n");
      out.write("\t\t\t\t\tonclick=\"regChk()\" />&nbsp; <input type=\"button\" value=\"다시입력\"\r\n");
      out.write("\t\t\t\t\tonclick=\"javascript:location.href='regFormImpl2.jsp\" />&nbsp; <input\r\n");
      out.write("\t\t\t\t\ttype=\"button\" value=\"취소\" onclick=\"regCancel()\" />&nbsp;\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
