/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-11-21 05:36:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.log;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction loginchk() {\r\n");
      out.write("\t\tvar regx = /^[a-zA-Z0-9]*$/;\r\n");
      out.write("\t\tvar id = document.form.id.value;\r\n");
      out.write("\t\tvar pass = document.form.pass.value;\r\n");
      out.write("\t\tif (id.length == 0 || id == null) {\r\n");
      out.write("\t\t\talert(\"아이디를 입력하시오\");\r\n");
      out.write("\t\t\tdocument.form.id.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!regx.test(id)) {\r\n");
      out.write("\t\t\talert(\"아이디는 영어, 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t\tdocument.form.id.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (pass.length < 6 || pass == null) {\r\n");
      out.write("\t\t\talert(\"비밀번호는 6글자이상입니다^^\");\r\n");
      out.write("\t\t\tdocument.form.pass.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!regx.test(pass)) {\r\n");
      out.write("\t\t\talert(\"비밀번호는 영어, 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t\tdocument.form.pass.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.form.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("b {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tfont-family: 돋움;\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputid {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\theight: 15px;\r\n");
      out.write("\tborder-color: green;\r\n");
      out.write("\tborder-width: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputpass {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\theight: 15px;\r\n");
      out.write("\tborder-color: green;\r\n");
      out.write("\tborder-width: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("\tborder-color: green;\r\n");
      out.write("\tborder-width: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>로그인 창</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<p align=\"right\">\r\n");
      out.write("\t<form action=\"loginProc.jsp\" method=\"post\" name=\"form\">\r\n");
      out.write("\t\t<b>아이디 : </b><input type=\"text\" size=\"10\" maxlength=\"15\" name=\"id\"\r\n");
      out.write("\t\t\tclass=\"inputid\">&nbsp; \r\n");
      out.write("\t\t<b>비밀번호 : </b><input type=\"password\"\r\n");
      out.write("\t\t\tsize=\"10\" maxlength=\"15\" name=\"pass\" class=\"inputpass\">&nbsp;&nbsp;\r\n");
      out.write("\t\t<img src=\"image/loginbutton.png\" width=\"50\" height=\"30\"\r\n");
      out.write("\t\t\talign=\"middle\" onclick=\"loginchk()\"> |&nbsp; \r\n");
      out.write("\t\t<a href=\"../member/regFormImpl.jsp\"> <b>회원가입</b></a>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<hr width=\"100%\">\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
